Add support for SOFAR 2200TL
klaasnicolaas/python-omnikinverter pull request #311
Opened 2022-12-23 11:02 UTC by darshkpatel

I tried using this library for my SOFAR inverter and noticed it was failing due to a space while parsing integer for the rated power substring it tries to read from the `myDeviceArray` string.

I have fixed that issue, updated the test to test this edge case too, and also updated the documentation adding support for SOFAR 2200TL🥂 

**Error Log for reference:**
``` py
  File "/usr/local/lib/python3.10/site-packages/omnikinverter/omnikinverter.py", line 184, in inverter
    return Inverter.from_js(data)
  File "/usr/local/lib/python3.10/site-packages/omnikinverter/models.py", line 177, in from_js
    solar_rated_power=get_value(4),
  File "/usr/local/lib/python3.10/site-packages/omnikinverter/models.py", line 158, in get_value
    return int(matches[position])
ValueError: invalid literal for int() with base 10: '2 00'
```

2022-12-23 12:39 UTC, klaasnicolaas requested changes
Could you make a separate test with its own data fixture?

2022-12-23 12:39 UTC, klaasnicolaas commented on omnikinverter/models.py
> +                            # Need to remove spaces before parsing int for SOFAR 2200TL
You can leave out the comment here

2022-12-23 13:15 UTC, darshkpatel commented on omnikinverter/models.py
> +                            # Need to remove spaces before parsing int for SOFAR 2200TL
Removed

2022-12-23 13:16 UTC, darshkpatel commented
> Could you make a separate test with its own data fixture?

Done in [b184a28](https://github.com/klaasnicolaas/python-omnikinverter/pull/311/commits/b184a28585b42149c9c0cd9040e891e9a154e9e7)

2023-01-20 13:06 UTC, klaasnicolaas approved these changes

2023-01-20 13:06 UTC, merged